<?php
/**
 * WooCommerce Multilevel Referral Main Class
 *
 * @package Multilevel_Referral_Plugin_For_WooCommerce
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
if ( ! class_exists( 'WooCommerce_Multilevel_Referral' ) ) {
	/**
	 * Main / front controller class
	 */
	class WooCommerce_Multilevel_Referral extends WooCommerce_Multilevel_Referral_Module {
		/**
		 * Readable properties. These should really be constants, but PHP doesn't allow class constants to be arrays.
		 *
		 * @var array
		 */
		protected static $readable_properties = array();
		/**
		 * Writeable properties.
		 *
		 * @var array
		 */
		protected static $writeable_properties = array();
		/**
		 * Modules array.
		 *
		 * @var array
		 */
		protected $modules;
		const VERSION    = '0.4';
		const PREFIX     = 'woocommerce_multilevel_referral_';
		const DEBUG_MODE = false;

		/*
		 * Magic methods
		 */
		/**
		 * Constructor
		 *
		 * @mvc Controller
		 */
		protected function __construct() {
			$this->register_hook_callbacks();
			if ( is_admin() ) {
				$this->modules = array(
					'WooCommerce_Multilevel_Referral_General_Settings'      => WooCommerce_Multilevel_Referral_General_Settings::get_instance(),
				);
			}
		}

		/*
		 * Static methods
		 */
		/**
		 * Enqueues CSS, JavaScript, etc
		 *
		 * @mvc Controller
		 */
		public static function load_resources() {
			global $wp_scripts;
			wp_register_script(
				self::PREFIX . 'jquery.mask',
				plugins_url( 'js/jquery.mask.js', __DIR__ ),
				array( 'jquery' ),
				self::VERSION,
				true
			);
			wp_register_script(
				self::PREFIX . 'whatsapp-button',
				plugins_url( 'js/whatsapp-button-min.js', __DIR__ ),
				array( 'jquery' ),
				self::VERSION,
				true
			);
			wp_register_script(
				self::PREFIX . 'sharing-script',
				plugins_url( 'js/share42-min.js', __DIR__ ),
				array( 'jquery' ),
				self::VERSION,
				true
			);
			$version = filemtime( WOOCOMMERCE_MULTILEVEL_REFERRAL_DIR . 'js/woocommerce-multilevel-referral-admin.js' );
			wp_register_script(
				self::PREFIX . 'woocommerce-multilevel-referral-admin',
				plugins_url( 'js/woocommerce-multilevel-referral-admin.js', __DIR__ ),
				array( 'jquery', 'jquery-ui-dialog' ),
				$version,
				true
			);
			wp_localize_script(
				self::PREFIX . 'woocommerce-multilevel-referral-admin',
				'woocommerce_multilevel_referral_ajax_admin',
				array(
					'ajaxurl' => admin_url( 'admin-ajax.php' ),
					'nonce'   => wp_create_nonce( 'woocommerce_multilevel_referral_ajax_nonce_action_admin' ),
					'URL'     => WOOCOMMERCE_MULTILEVEL_REFERRAL_URL,
				)
			);
			$version = filemtime( WOOCOMMERCE_MULTILEVEL_REFERRAL_DIR . 'js/woocommerce-multilevel-referral.js' );
			wp_register_script(
				self::PREFIX . 'woocommerce-multilevel-referral',
				plugins_url( 'js/woocommerce-multilevel-referral.js', __DIR__ ),
				array( 'jquery' ),
				$version,
				true
			);
				wp_localize_script(
					self::PREFIX . 'woocommerce-multilevel-referral',
					'woocommerce_multilevel_referral_ajax',
					array(
						'ajaxurl' => admin_url( 'admin-ajax.php' ),
						'nonce'   => wp_create_nonce( 'woocommerce_multilevel_referral_ajax_nonce_action' ),
						'URL'     => WOOCOMMERCE_MULTILEVEL_REFERRAL_URL,
					)
				);
			$version = filemtime( WOOCOMMERCE_MULTILEVEL_REFERRAL_DIR . 'css/admin.css' );
			wp_register_style(
				self::PREFIX . 'admin',
				plugins_url( 'css/admin.css', __DIR__ ),
				array(),
				$version,
				'all'
			);
			$version = filemtime( WOOCOMMERCE_MULTILEVEL_REFERRAL_DIR . 'css/style.css' );
			wp_register_style(
				self::PREFIX . 'front',
				plugins_url( 'css/style.css', __DIR__ ),
				array(),
				$version,
				'all'
			);
			wp_enqueue_script( self::PREFIX . 'jquery.mask' );
			if ( is_admin() ) {

				wp_enqueue_style( self::PREFIX . 'admin' );
				wp_enqueue_script( self::PREFIX . 'woocommerce-multilevel-referral-admin' );
			} else {
				wp_enqueue_style( self::PREFIX . 'front' );
				wp_enqueue_script( self::PREFIX . 'woocommerce-multilevel-referral' );
				wp_enqueue_script( self::PREFIX . 'whatsapp-button' );
				wp_enqueue_script( self::PREFIX . 'sharing-script' );
			}
		}
		/**
		 * Clears caches of content generated by caching plugins like WP Super Cache
		 *
		 * @mvc Model
		 */
		protected static function clear_caching_plugins() {
			// WP Super Cache.
			if ( function_exists( 'wp_cache_clear_cache' ) ) {
				wp_cache_clear_cache();
			}
			// W3 Total Cache.
			if ( class_exists( 'W3_Plugin_TotalCacheAdmin' ) ) {
				$w3_total_cache = w3_instance( 'W3_Plugin_TotalCacheAdmin' );
				if ( method_exists( $w3_total_cache, 'flush_all' ) ) {
					$w3_total_cache->flush_all();
				}
			}
		}

		/*
		 * Instance methods
		 */
		/**
		 * Prepares sites to use the plugin during single or network-wide activation.
		 *
		 * @mvc Controller
		 *
		 * @param bool $network_wide Network wide activation.
		 */
		public function activate( $network_wide ) {
			$woocommerce_multilevel_referral_program = WooCommerce_Multilevel_Referral_Program::get_instance();
			$woocommerce_multilevel_referral_program->create_table();
			$obj_referal_users = WooCommerce_Multilevel_Referral_Users::get_instance();
			$obj_referal_users->create_table();
			if ( $network_wide && is_multisite() ) {
				$sites = get_sites( array( 'limit' => false ) );
				foreach ( $sites as $site ) {
					switch_to_blog( $site->blog_id );
					$this->single_activate( $network_wide );
					restore_current_blog();
				}
			} else {
				$this->single_activate( $network_wide );
			}
			$joining_mail_template        = get_option( 'joining_mail_template', '' );
			$joining_mail_subject         = get_option( 'joining_mail_subject', __( 'Referral Program Team', 'multilevel-referral-plugin-for-woocommerce' ) );
			$joining_mail_heading         = get_option( 'joining_mail_heading', __( 'Referral Program Team', 'multilevel-referral-plugin-for-woocommerce' ) );
			$referral_user_template       = get_option( 'referral_user_template', '' );
			$referral_user_subject        = get_option( 'referral_user_subject', __( 'Referral Program Team', 'multilevel-referral-plugin-for-woocommerce' ) );
			$referral_user_heading        = get_option( 'referral_user_heading', __( 'Referral Program Team', 'multilevel-referral-plugin-for-woocommerce' ) );
			$expire_notification_template = get_option( 'expire_notification_template', '' );
			$expire_notification_subject  = get_option( 'expire_notification_subject', __( 'Referral Program Team', 'multilevel-referral-plugin-for-woocommerce' ) );
			$expire_notification_heading  = get_option( 'expire_notification_heading', __( 'Referral Program Team', 'multilevel-referral-plugin-for-woocommerce' ) );
			$j_html                       = 'Hello {first_name} {last_name},<br>
                <br>
				Thanks for joining our Referral Program. Your Referral code is :<strong>{referral_code}</strong>. You can share it and earn points on the purchase by your referral users.<br>
				Regards,<br>
				<br>
				Referral Team';
							$r_html       = 'Hello User,<br><br>
				{first_name} {last_name} is invited you to join their referral program. You can join them by [referral_link text="click here"].<br>
				<br>
				Regards,<br>
				<br>
				Referral Team.';
							$e_html       = 'Hello {first_name} {last_name},<br>
				<br>
				Your Store Reward Credits come with a validity of {validity_period}. You have {available_credits} credits as on {today_date}.<strong>Redeem your points before they expire.</strong>
				<table>
				<tbody>
				<tr>
				<th>Month</th>
				<th>Total credits about to expire</th>
				<th>Date of expiry</th>
				</tr>
				<tr>
				<td>{expire_month}</td>
				<td>{expire_credits}</td>
				<td>{expire_date}</td>
				</tr>
				</tbody>
				</table>';
			if ( '' === stripslashes( $joining_mail_template ) ) {
				update_option( 'joining_mail_template', addslashes( $j_html ) );
			}
			if ( '' === stripslashes( $referral_user_template ) ) {
				update_option( 'referral_user_template', addslashes( $r_html ) );
			}
			if ( '' === stripslashes( $expire_notification_template ) ) {
				update_option( 'expire_notification_template', addslashes( $e_html ) );
			}
			$this->woocommerce_multilevel_referral_create_pre_banners();
		}
		/**
		 * Runs activation code on a new WPMS site when it's created
		 *
		 * @mvc Controller
		 *
		 * @param int $blog_id Blog ID.
		 */
		public function activate_new_site( $blog_id ) {
			switch_to_blog( $blog_id );
			$this->single_activate( true );
			restore_current_blog();
		}
		/**
		 * Prepares a single blog to use the plugin
		 *
		 * @mvc Controller
		 *
		 * @param bool $network_wide Network wide activation.
		 */
		protected function single_activate( $network_wide ) {
			foreach ( $this->modules as $module ) {
				$module->activate( $network_wide );
			}
			flush_rewrite_rules();
		}
		/**
		 * Rolls back activation procedures when de-activating the plugin
		 *
		 * @mvc Controller
		 */
		public function deactivate() {
			foreach ( $this->modules as $module ) {
				$module->deactivate();
			}
			flush_rewrite_rules();
		}
		/**
		 * Register callbacks for actions and filters
		 *
		 * @mvc Controller
		 */
		public function register_hook_callbacks() {
			global $woocommerce_multilevel_referral_cache;
			if ( ! is_array( $woocommerce_multilevel_referral_cache ) ) {
				$woocommerce_multilevel_referral_cache = array();
			}
			if ( is_admin() ) {
				WooCommerce_Multilevel_Referral_General_Settings::get_instance();
				WooCommerce_Multilevel_Referral_User::get_instance();
				WooCommerce_Multilevel_Referral_Settings::get_instance();
				add_action( 'pre_user_query', array( $this, 'in_active_user' ) );
			}
			add_action( 'wpmu_new_blog', __CLASS__ . '::activate_new_site' );
			add_action( 'wp_enqueue_scripts', __CLASS__ . '::load_resources', 99 );
			add_action( 'admin_enqueue_scripts', __CLASS__ . '::load_resources' );
			add_action( 'init', array( $this, 'init' ) );
			add_action( 'init', array( $this, 'upgrade' ), 11 );
			add_filter( 'woocommerce_email_classes', array( $this, 'woocommerce_multilevel_referral_referral_join_email' ) );
			add_action( 'woocommerce_email', array( $this, 'woocommerce_multilevel_referral_custom_mail_handler' ) );
			add_action( 'admin_init', array( $this, 'woocommerce_multilevel_referral_custom_activate_plugin' ) );
			add_action( 'upgrader_process_complete', array( $this, 'woocommerce_multilevel_referral_upgrade_completed' ), 10, 2 );
		}
		/**
		 * Display new feature notice.
		 */
		public function woocommerce_multilevel_referral_new_feature_notice() {
			require_once WOOCOMMERCE_MULTILEVEL_REFERRAL_DIR . 'views/admin/new-features.php';
		}
		/**
		 * Handle upgrade completion.
		 *
		 * @param WP_Upgrader $upgrader_object Upgrader object.
		 * @param array       $options Options.
		 */
		public function woocommerce_multilevel_referral_upgrade_completed( $upgrader_object, $options ) {
		}
		/**
		 * Custom activate plugin.
		 */
		public function woocommerce_multilevel_referral_custom_activate_plugin() {
			global $wpdb;
			$pluginslug = isset( $_GET['plugin_slug'] ) ? sanitize_text_field( wp_unslash( $_GET['plugin_slug'] ) ) : '';
			// Check user capabilities first.
			if ( ! current_user_can( 'activate_plugins' ) ) {
				return;
			}
			// Fail early if nonce is missing or invalid.
			if ( ! isset( $_GET['woocommerce_multilevel_referral_addons_active_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['woocommerce_multilevel_referral_addons_active_nonce'] ) ), $pluginslug ) ) {
				return;
			}
			// Nonce is valid, proceed with plugin activation.
			$result = activate_plugin( isset( $_GET['plugin'] ) ? sanitize_text_field( wp_unslash( $_GET['plugin'] ) ) : '' );
			if ( is_wp_error( $result ) ) {
				add_action(
					'admin_notices',
					function () {
						echo '<div class="notice notice-error is-dismissible" ><p>' . esc_html_e( 'Something went wrong! Try again later!', 'multilevel-referral-plugin-for-woocommerce' ) . '</p></div>';
					},
					11
				);
			}
			$woocommerce_multilevel_referral_version = get_option( 'woocommerce_multilevel_referral_version', 0 );
			if ( WOOCOMMERCE_MULTILEVEL_REFERRAL_VER !== $woocommerce_multilevel_referral_version ) {
				add_action( 'admin_notices', array( $this, 'woocommerce_multilevel_referral_new_feature_notice' ) );
				$table_name = $wpdb->prefix . 'referal_program';
				$sql        = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '" . $table_name . "' AND column_name = 'is_transfer'";
				// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
				$istransfer = $wpdb->get_results( "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = {$wpdb->prefix}referal_program AND column_name = 'is_transfer'" );
				if ( empty( $istransfer ) ) {
					// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange
					$sql = $wpdb->query( "ALTER TABLE {$wpdb->prefix}referal_program ADD is_transfer tinyint(1) NOT NULL AFTER redeems" );
				}
				update_option( 'woocommerce_multilevel_referral_version', WOOCOMMERCE_MULTILEVEL_REFERRAL_VER );
			}
			if ( woocommerce_multilevel_referral_fs()->is_free_plan() ) {
				$surl  = isset( $_SERVER['REQUEST_URI'] ) ? sanitize_text_field( wp_unslash( $_SERVER['REQUEST_URI'] ) ) : '';
				$ptype = isset( $_GET['post_type'] ) ? sanitize_text_field( wp_unslash( $_GET['post_type'] ) ) : '';
				if ( false !== strpos( $surl, 'post-new.php' ) && 'wc_ml_ref_banner' === $ptype ) {
					wp_safe_redirect( admin_url( '/edit.php?post_type=' . $ptype ) );
					exit();
				}
			}
		}
		/**
		 * Initializes variables
		 *
		 * @mvc Controller
		 */
		public function init() {
			try {
				if ( is_admin() ) {
					$nonce    = isset( $_GET['_wpnonce'] ) ? sanitize_text_field( wp_unslash( $_GET['_wpnonce'] ) ) : '';
					$url_data = woocommerce_multilevel_referral_get_query_vars();
					if ( isset( $url_data['search_by_join_sdate'] ) && '' !== $url_data['search_by_join_sdate'] ) {
						$sdate_raw = sanitize_text_field( wp_unslash( $url_data['search_by_join_sdate'] ) );
						$sdate     = DateTime::createFromFormat( 'Y-m-d', $sdate_raw );
						if ( ! $sdate || $sdate_raw !== $sdate->format( 'Y-m-d' ) ) {
							add_action(
								'woocommerce_multilevel_referral_notices',
								function () {
									echo '<div class="notice notice-error"><p>Invalid start date supplied. Please use YYYY-MM-DD.</p></div>';
								}
							);
						}
					}
					if ( isset( $url_data['search_by_join_edate'] ) && '' !== $url_data['search_by_join_edate'] ) {
						$edate_raw = sanitize_text_field( wp_unslash( $url_data['search_by_join_edate'] ) );
						$edate     = DateTime::createFromFormat( 'Y-m-d', $edate_raw );
						if ( ! $edate || $edate_raw !== $edate->format( 'Y-m-d' ) ) {
							add_action(
								'woocommerce_multilevel_referral_notices',
								function () {
									echo '<div class="notice notice-error"><p>Invalid end date supplied. Please use YYYY-MM-DD.</p></div>';
								}
							);
						}
					}
					if ( wp_verify_nonce( $nonce, 'woocommerce_multilevel_referral_ajax_nonce_action_admin' ) ) {
						if ( isset( $_GET['load_referral_user_list'] ) ) {
							$woocommerce_multilevel_referral_program = WooCommerce_Multilevel_Referral_Program::get_instance();
							$referral_users                          = $woocommerce_multilevel_referral_program->get_referral_user_list( sanitize_text_field( wp_unslash( $_GET['load_referral_user_list'] ) ) );
							echo wp_kses( self::render_template( 'admin/referral-list-popup.php', array( 'woocommerce_multilevel_referral_referral_users' => $referral_users ) ), woocommerce_multilevel_referral_get_wp_fs_allow_html( array( 'ul', 'li', 'div', 'span', 'a' ) ) );
							die();
						}
					}
					if ( isset( $_GET['remove_referral_user'] ) ) {
						$woocommerce_multilevel_referral_program = WooCommerce_Multilevel_Referral_Program::get_instance();
						$parent_referral_user                    = $woocommerce_multilevel_referral_program->remove_referral_user( sanitize_text_field( wp_unslash( $_GET['remove_referral_user'] ) ) );
						$referral_users                          = $woocommerce_multilevel_referral_program->get_referral_user_list( $parent_referral_user );
						echo wp_kses( self::render_template( 'admin/referral-list-popup.php', array( 'referral_users' => $referral_users ) ), woocommerce_multilevel_referral_get_wp_fs_allow_html( array( 'ul', 'li', 'div', 'span', 'a' ) ) );
						die();
					}
					if ( isset( $_GET['active_referral_user'] ) ) {
						$obj_referal_users    = WooCommerce_Multilevel_Referral_Users::get_instance();
						$parent_referral_user = $obj_referal_users->active_referral_user( sanitize_text_field( wp_unslash( $_GET['active_referral_user'] ) ) );
						die();
					}
					if ( isset( $_POST['action'] ) && 'getReferralsDetails' === $_POST['action'] ) {
						$arr_return = array(
							'result' => 'failed',
							'data'   => __( 'Invalid Request', 'multilevel-referral-plugin-for-woocommerce' ),
						);
						if ( isset( $_POST['userId'] ) && is_numeric( $_POST['userId'] ) && 0 !== (int) $_POST['userId'] ) {
							$user_id              = sanitize_text_field( wp_unslash( $_POST['userId'] ) );
							$obj_referal_users    = WooCommerce_Multilevel_Referral_Users::get_instance();
							$referral_details     = $obj_referal_users->fnGetReferralsIdsByLevel( $user_id );
							$arr_return['result'] = 'success';
							$arr_return['data']   = $referral_details;
						}
						echo wp_json_encode( $arr_return );
						die();
					}
					if ( isset( $_GET['getReferralsCount'] ) ) {
						$obj_referal_users = WooCommerce_Multilevel_Referral_Users::get_instance();
						$user_id           = sanitize_text_field( wp_unslash( $_GET['getReferralsCount'] ) );
						$referral_count    = $obj_referal_users->fnGetFollowersCount( $user_id );
						if ( is_numeric( $referral_count ) ) {
							update_user_meta( $user_id, 'total_referrals', $referral_count );
							echo esc_html( $referral_count );
						} else {
							echo '!';
						}
						die;
					}
					if ( isset( $_GET['changeReferralsLevel'] ) ) {
						$obj_referal_users = WooCommerce_Multilevel_Referral_Users::get_instance();
						$user_id           = sanitize_text_field( wp_unslash( $_GET['changeReferralsLevel'] ) );
						$obj_referal_users->change_referral_user_level( $user_id );
						unset( $_GET['changeReferralsLevel'] );
						// Sanitize all GET parameters before using in add_query_arg.
						$sanitized_get = array();
						foreach ( $_GET as $key => $value ) {
							$sanitized_key                   = sanitize_key( $key );
							$sanitized_get[ $sanitized_key ] = sanitize_text_field( wp_unslash( $value ) );
						}
						$url = add_query_arg( $sanitized_get, admin_url( 'admin.php' ) );
						wp_safe_redirect( $url );
						exit();
					}
				}
			} catch ( Exception $exception ) {
				add_notice( __METHOD__ . ' error: ' . $exception->getMessage(), 'error' );
			}
			/* BANNER CODE */
			$this->registerCustomPostType( 'Banner', 'Banners', 'wc_ml_ref_banner', array( 'title', 'thumbnail', 'excerpt' ) );
			add_filter( 'manage_wc_ml_ref_banner_posts_columns', __CLASS__ . '::fnAddBannerColumn' );
			add_filter( 'manage_wc_ml_ref_banner_posts_custom_column', __CLASS__ . '::fnManageBannerColumn', 10, 2 );
			add_action( 'edit_form_top', __CLASS__ . '::fnAddAllBannerButton', 11, 1 );
			add_action( 'trashed_post', __CLASS__ . '::fnBeforeDeleteBanner' );
			add_filter( 'post_row_actions', __CLASS__ . '::remove_banner_row_actions', 10, 2 );
			add_filter( 'display_post_states', __CLASS__ . '::fnDisplayPostState', 10, 2 );
			add_filter( 'bulk_actions-edit-wc_ml_ref_banner', __CLASS__ . '::banner_bulk_actions' );
			add_filter( 'parent_file', __CLASS__ . '::fnActiveParentMenu' );
			add_filter( 'submenu_file', __CLASS__ . '::fnActiveSubMenu', 10, 2 );
			$error = get_transient( 'banner_delete_error' );
			if ( '' !== $error ) {
				add_action(
					'admin_notices',
					function () use ( $error ) {
						echo '<div class="notice notice-error is-dismissible" ><p>' . esc_html( $error ) . '</p></div>';
					},
					11
				);
				delete_transient( 'banner_delete_error' );
			}
		}
		/* Banner Module functions */
		/**
		 * Active parent menu.
		 *
		 * @param string $files Files.
		 *
		 * @return string Modified files.
		 */
		public static function fnActiveParentMenu( $files ) {
			$url_data = woocommerce_multilevel_referral_get_query_vars();
			if ( isset( $url_data['post_type'] ) && 'wc_ml_ref_banner' === $url_data['post_type'] ) {
				$files = 'woocommerce';
			}
			return $files;
		}
		/**
		 * Active sub menu.
		 *
		 * @param string $submenu_file Submenu file.
		 * @param string $parent_file Parent file.
		 *
		 * @return string Modified submenu file.
		 */
		public static function fnActiveSubMenu( $submenu_file, $parent_file ) {
			global $submenu;
			$url_data = woocommerce_multilevel_referral_get_query_vars();
			if ( isset( $url_data['post_type'] ) && 'wc_ml_ref_banner' === $url_data['post_type'] ) {
				$submenu_file = '';
			}
			return $submenu_file;
		}
		/**
		 * Get page by exact title.
		 *
		 * @param string $title Page title.
		 *
		 * @return WP_Post|null Post object or null.
		 */
		public function get_page_by_title_exact( $title ) {
			$args  = array(
				'post_type'      => 'wc_ml_ref_banner',
				'post_status'    => 'publish',
				'posts_per_page' => 1,
			);
			$query = new WP_Query( $args );
			foreach ( $query->posts as $post ) {
				if ( $title === $post->post_title ) {
					return $post;
				}
			}
			return null;
		}
		/**
		 * Create pre banners.
		 */
		public function woocommerce_multilevel_referral_create_pre_banners() {
			$all_banners     = $this->woocommerce_multilevel_referral_scandir( WOOCOMMERCE_MULTILEVEL_REFERRAL_DIR . 'images/banners' );
			$arr_pre_banners = array();
			if ( is_array( $all_banners ) && count( $all_banners ) > 0 ) {
				foreach ( $all_banners as $name => $fullpath ) {
					$banner_id = '';
					$filename  = basename( $fullpath );
					$filetype  = wp_check_filetype( $fullpath );
					if ( 'image/jpeg' === $filetype['type'] || 'image/png' === $filetype['type'] || 'image/gif' === $filetype['type'] ) {
						$title       = ucwords( str_replace( '-', ' ', pathinfo( $filename, PATHINFO_FILENAME ) ) );
						$description = __( 'This is the promotional banner', 'multilevel-referral-plugin-for-woocommerce' );
						$arr_file    = array(
							'name'     => trim( $filename ),
							'tmp_name' => $fullpath,
							'type'     => $filetype['type'],
							'size'     => filesize( $fullpath ),
						);
						$banner      = $this->get_page_by_title_exact( $title );
						if ( ! $banner ) {
							$banner_id = wp_insert_post(
								array(
									'post_title'   => $title,
									'post_type'    => 'wc_ml_ref_banner',
									'post_excerpt' => $description,
									'post_status'  => 'publish',
								)
							);
						} else {
							$banner_id = $banner->ID;
						}
						if ( '' !== $banner_id && 0 !== $banner_id ) {
							$u_image = false;
							if ( has_post_thumbnail( $banner_id ) ) {
								$attachment_id = get_post_thumbnail_id( $banner_id );
								$image_data    = wp_get_attachment_image_src( $attachment_id, 'full' );
								if ( intval( $image_data[1] ) < 1200 ) {
									wp_delete_attachment( $attachment_id, true );
									$u_image = true;
								}
							} else {
								$u_image = true;
							}
							if ( $u_image ) {
								$attach_id = $this->woocommerce_multilevel_referral_banner_upload( $banner_id, $arr_file );
								if ( 0 !== $attach_id ) {
									set_post_thumbnail( $banner_id, $attach_id );
								}
							}
							array_push( $arr_pre_banners, $banner_id );
						}
					}
					if ( is_array( $arr_pre_banners ) && count( $arr_pre_banners ) > 0 ) {
						update_option( 'woocommerce_multilevel_referral_pre_banners', $arr_pre_banners, true );
						update_option( 'woocommerce_multilevel_referral_default_banners', array_chunk( $arr_pre_banners, 3 )[0], true );
					}
				}
			}
		}
		/**
		 * Upload banner.
		 *
		 * @param int   $post_id Post ID.
		 * @param array $file_array File array.
		 *
		 * @return int Attachment ID or 0 on failure.
		 */
		public function woocommerce_multilevel_referral_banner_upload( $post_id, $file_array ) {
			if ( ! function_exists( 'media_handle_upload' ) ) {
				require_once ABSPATH . 'wp-admin/includes/image.php';
				require_once ABSPATH . 'wp-admin/includes/file.php';
				require_once ABSPATH . 'wp-admin/includes/media.php';
			}
			$id = media_handle_sideload( $file_array, $post_id );
			if ( ! is_wp_error( $id ) ) {
				return $id;
			}
			return 0;
		}
		/**
		 * Banner bulk actions.
		 *
		 * @param array $actions Actions.
		 *
		 * @return array Modified actions.
		 */
		public static function banner_bulk_actions( $actions ) {
			unset( $actions['trash'] );
			return $actions;
		}
		/**
		 * Before delete banner.
		 *
		 * @param int $post_id Post ID.
		 */
		public static function fnBeforeDeleteBanner( $post_id ) {
			global $post_type;
			if ( 'wc_ml_ref_banner' === $post_type ) {
				$arr_banners = get_option( 'woocommerce_multilevel_referral_pre_banners' );
				if ( is_array( $arr_banners ) && count( $arr_banners ) > 0 ) {
					if ( in_array( $post->ID, $arr_banners, true ) ) {
						wp_untrash_post( $post_id );
						set_transient( 'banner_delete_error', 'You can not delete pre-defined banners', 1000 );
					}
				}
				return;
			}
		}
		/**
		 * Remove banner row actions.
		 *
		 * @param array   $actions Actions.
		 * @param WP_Post $post Post object.
		 *
		 * @return array Modified actions.
		 */
		public static function remove_banner_row_actions( $actions, $post ) {
			if ( get_post_type() === 'wc_ml_ref_banner' ) {
				$arr_banners = get_option( 'woocommerce_multilevel_referral_pre_banners' );
				if ( is_array( $arr_banners ) && count( $arr_banners ) > 0 ) {
					if ( in_array( $post->ID, $arr_banners, true ) ) {
						unset( $actions['trash'] );
					}
					unset( $actions['view'] );
				}
				if ( woocommerce_multilevel_referral_fs()->is_free_plan() ) {
					$arr_default_banners = get_option( 'woocommerce_multilevel_referral_default_banners' );
					if ( is_array( $arr_default_banners ) && count( $arr_default_banners ) > 0 ) {
						if ( ! in_array( $post->ID, $arr_default_banners, true ) ) {
							foreach ( $actions as $key => $value ) {
								$actions[ $key ] = sprintf( '<a href="#" class="%s">%s</a>', 'premium_featured', wp_strip_all_tags( $value ) );
							}
						}
					}
				}
			}
			return $actions;
		}
		/**
		 * Display post state.
		 *
		 * @param array   $post_states Post states.
		 * @param WP_Post $post Post object.
		 */
		public static function fnDisplayPostState( $post_states, $post ) {
			$arr_default_banners = get_option( 'woocommerce_multilevel_referral_default_banners' );
			$url_data            = woocommerce_multilevel_referral_get_query_vars();
			if ( is_array( $arr_default_banners ) && count( $arr_default_banners ) > 0 ) {
				if ( ! in_array( $post->ID, $arr_default_banners, true ) && ( isset( $url_data['post_type'] ) && sanitize_text_field( wp_unslash( $url_data['post_type'] ) ) === 'wc_ml_ref_banner' ) ) {
					echo '&nbsp;<span>( ';
					echo esc_html_e( 'Premium Banner', 'multilevel-referral-plugin-for-woocommerce' );
					echo ' )</span>&nbsp;';
				}
			}
		}
		/**
		 * Add all banner button.
		 *
		 * @param WP_Post $post Post object.
		 */
		public static function fnAddAllBannerButton( $post ) {
			if ( 'wc_ml_ref_banner' === $post->post_type ) {
				echo ' <a href="' . esc_url( admin_url( 'edit.php?post_type=wc_ml_ref_banner' ) ) . '" class="add-new-h2">' . esc_html_e( 'All Banners', 'multilevel-referral-plugin-for-woocommerce' ) . '</a>';
			}
		}
		/**
		 * Add banner column.
		 *
		 * @param array $columns Columns.
		 *
		 * @return array Modified columns.
		 */
		public static function fnAddBannerColumn( $columns ) {
			$columns['img'] = 'Banner';
			return $columns;
		}
		/**
		 * Manage banner column.
		 *
		 * @param string $column_name Column name.
		 * @param int    $post_id Post ID.
		 */
		public static function fnManageBannerColumn( $column_name, $post_id ) {
			if ( 'img' === $column_name ) {
				echo get_the_post_thumbnail( $post_id, 'medium' );
			}
		}

		/*
		 * Banner Module functions End
		 */
		/**
		 * Add additional restriction on user list.
		 *
		 * @param WP_User_Query $query User query.
		 */
		public function in_active_user( $query ) {
			global $wpdb;
			$where    = '';
			$url_data = woocommerce_multilevel_referral_get_query_vars();
			if ( ! empty( $url_data ) ) {
				$ordr = isset( $url_data['order'] ) ? sanitize_text_field( wp_unslash( $url_data['order'] ) ) : '';
				if ( isset( $url_data['page'] ) && 'wc_referral' === $url_data['page'] ) {
					$query->query_from = $query->query_from . ' JOIN ' . $wpdb->prefix . 'referal_users AS ru ON ru.user_id = ' . $wpdb->users . '.ID ';
					$where             = $query->query_where . ' AND ru.active = 1 ';
				}
				if ( isset( $url_data['user_status'] ) && '0' === $url_data['user_status'] ) {
					$query->query_fields = $query->query_fields . ', ru.update_date ';
					$where               = $query->query_where . ' AND ru.active = 0 ';
					if ( isset( $url_data['orderby'] ) && 'deactivate_date' === $url_data['orderby'] ) {
						$query->query_orderby = 'ORDER BY ru.update_date ' . esc_sql( $ordr );
					}
				}
				if ( isset( $url_data['search_by_join_sdate'] ) && '' !== $url_data['search_by_join_sdate'] ) {
					$sdate_raw = sanitize_text_field( wp_unslash( $url_data['search_by_join_sdate'] ) );
					$sdate     = DateTime::createFromFormat( 'Y-m-d', $sdate_raw );
					if ( $sdate && $sdate_raw === $sdate->format( 'Y-m-d' ) ) {
						$where .= $wpdb->prepare( ' AND ru.join_date >= %s ', $sdate->format( 'Y-m-d' ) . ' 00:00:00' );
					}
				}
				if ( isset( $url_data['search_by_join_edate'] ) && '' !== $url_data['search_by_join_edate'] ) {
					$edate_raw = sanitize_text_field( wp_unslash( $url_data['search_by_join_edate'] ) );
					$edate     = DateTime::createFromFormat( 'Y-m-d', $edate_raw );
					if ( $edate && $edate_raw === $edate->format( 'Y-m-d' ) ) {
						$where .= $wpdb->prepare( ' AND ru.join_date <= %s ', $edate->format( 'Y-m-d' ) . ' 23:59:59' );
					}
				}
				if ( $where ) {
					$query->query_where = $where;
				}
				return $query;
			}
		}
		/**
		 *  Add email settings to WooCommerce Email settings page.
		 *
		 *  @param array $email_classes List of register email settings.
		 *
		 *  @return array Return new array list.
		 **/
		public function woocommerce_multilevel_referral_referral_join_email( $email_classes ) {
			// include our custom email class.
			require_once __DIR__ . '/class-woocommerce-multilevel-referral-mail.php';
			// add the email class to the list of email classes that WooCommerce loads.
			$email_classes['WooCommerce_Multilevel_Referral_Joining_User'] = new WooCommerce_Multilevel_Referral_Mail();
			return $email_classes;
		}
		/**
		 * Custom mail handler.
		 *
		 * @param WC_Emails $emails_obj Emails object.
		 */
		public function woocommerce_multilevel_referral_custom_mail_handler( $emails_obj ) {
			add_action( 'woocommerce_multilevel_referral_joining_user_notification', array( $emails_obj->emails['WooCommerce_Multilevel_Referral_Joining_User'], 'trigger' ), 10, 6 );
			add_action( 'woocommerce_multilevel_referral_user_reminder', array( $emails_obj->emails['WooCommerce_Multilevel_Referral_Joining_User'], 'reminder' ), 10, 9 );
		}
		/**
		 *  Sending mail for new activated user.
		 *
		 *  @param int    $to Email id of user.
		 *  @param string $first_name User's first name.
		 *  @param string $last_name User's last name.
		 *  @param string $code New generated referral code for new user.
		 *  @param string $template Email template based on user.
		 *  @param int    $user_id Parent user id.
		 *
		 *  @return void
		 **/
		public function woocommerce_multilevel_referral_joining_mail( $to, $first_name, $last_name, $code, $template, $user_id ) {
			$obj_mails = new WC_Emails();
			$email     = $obj_mails->emails['WooCommerce_Multilevel_Referral_Joining_User'];
			$email->trigger( $to, $first_name, $last_name, $code, $template, $user_id );
		}
		/**
		 * Checks if the plugin was recently updated and upgrades if necessary
		 *
		 * @mvc Controller
		 *
		 * @param string $db_version Database version.
		 */
		public function upgrade( $db_version = 0 ) {
			self::clear_caching_plugins();
		}
		/**
		 * Checks that the object is in a correct state.
		 *
		 * @mvc Model
		 *
		 * @param string $property An individual property to check, or 'all' to check all of them.
		 *
		 * @return bool
		 */
		protected function is_valid( $property = 'all' ) {
			return true;
		}
		/**
		 * Register custom post type.
		 *
		 * @param string $title Title.
		 * @param string $title_p Title plural.
		 * @param string $name Post type name.
		 * @param array  $supports Post supports.
		 * @param bool   $is_show Show in menu.
		 *
		 * @return string Post type name.
		 */
		public function registerCustomPostType( $title, $title_p, $name, $supports, $is_show = false ) {
			$labels = array(
				'name'               => _x( 'Add New Banner', '', 'multilevel-referral-plugin-for-woocommerce' ),
				'singular_name'      => $title,
				// translators: %s is the title.
				'add_new'            => sprintf( _x( 'Add New %s', '', 'multilevel-referral-plugin-for-woocommerce' ), $title ),
				// translators: %s is the title.
				'add_new_item'       => sprintf( __( 'Add New %s', 'multilevel-referral-plugin-for-woocommerce' ), $title ),
				// translators: %s is the title.
				'edit_item'          => sprintf( __( 'Edit %s', 'multilevel-referral-plugin-for-woocommerce' ), $title ),
				// translators: %s is the title.
				'new_item'           => sprintf( __( 'New %s', 'multilevel-referral-plugin-for-woocommerce' ), $title ),
				// translators: %s is the title.
				'view_item'          => sprintf( __( 'View %s', 'multilevel-referral-plugin-for-woocommerce' ), $title ),
				// translators: %s is the title.
				'search_items'       => sprintf( __( 'Search %s', 'multilevel-referral-plugin-for-woocommerce' ), $title ),
				// translators: %s is the title.
				'not_found'          => sprintf( __( 'No %s found', 'multilevel-referral-plugin-for-woocommerce' ), $title ),
				// translators: %s is the title.
				'not_found_in_trash' => sprintf( __( 'No %s found in Trash', 'multilevel-referral-plugin-for-woocommerce' ), $title ),
				'parent_item_colon'  => '',
				'menu_name'          => "$title_p",
			);
			$args   = array(
				'labels'              => $labels,
				'public'              => true,
				'show_in_menu'        => $is_show,
				'show_in_nav_menus'   => true,
				'publicly_queryable'  => true,
				'query_var'           => true,
				'rewrite'             => true,
				'capability_type'     => 'post',
				'has_archive'         => false,
				'hierarchical'        => false,
				'exclude_from_search' => false,
				'supports'            => $supports,
			);
			register_post_type( $name, $args );
			return $name;
		}
		/**
		 * Scan files in directory.
		 *
		 * @param string     $path Directory path.
		 * @param array|null $extensions File extensions.
		 * @param int        $depth Depth.
		 * @param string     $relative_path Relative path.
		 *
		 * @return array|false Array of files or false on failure.
		 */
		public function woocommerce_multilevel_referral_scandir( $path, $extensions = null, $depth = 0, $relative_path = '' ) {
			if ( ! is_dir( $path ) ) {
				return false;
			}
			if ( $extensions ) {
				$extensions  = (array) $extensions;
				$_extensions = implode( '|', $extensions );
			}
			$relative_path = trailingslashit( $relative_path );
			if ( '/' === $relative_path ) {
				$relative_path = '';
			}
			$results = scandir( $path );
			$files   = array();
			foreach ( $results as $result ) {
				if ( '.' === $result[0] ) {
					continue;
				}
				if ( is_dir( $path . '/' . $result ) ) {
					if ( ! $depth || 'CVS' === $result ) {
						continue;
					}
					$found = $this->woocommerce_multilevel_referral_scandir( $path . '/' . $result, $extensions, $depth - 1, $relative_path . $result );
					$files = array_merge_recursive( $files, $found );
				} elseif ( ! $extensions || preg_match( '~\.(' . $_extensions . ')$~', $result ) ) {
					$files[ $relative_path . $result ] = $path . '/' . $result;
				}
			}
			return $files;
		}
	} // end WooCommerce_Multilevel_Referal
}
